name: Deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Node environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build rust lib and install packages
        run: bash build.sh

      - name: Build vite project
        run: npm run build -- --base=/${{ github.event.repository.name }}/

      - name: Deploy on gh-pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
